crypto_lakehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ':memory:'

      extensions:
        - httpfs
        - parquet

      settings:
        s3_endpoint: 'minio:9000'
        s3_access_key_id: 'minioadmin'
        s3_secret_access_key: 'minioadmin'
        s3_use_ssl: false
        s3_url_style: 'path'